import logging

from datamodel.input.staticinnerbase import *

class BusInitialStatusBase(BusInitialStatusBaseBase): pass

class ShuntInitialStatusBase(ShuntInitialStatusBaseBase): pass

class DispatchableDevices_SimpleProducingConsumingDevicesInitialStatusBase(DispatchableDevices_SimpleProducingConsumingDevicesInitialStatusBaseBase): pass

class ACTransmissionLineInitialStatusBase(ACTransmissionLineInitialStatusBaseBase): pass

class TwoWindingTransformerInitialStatusBase(TwoWindingTransformerInitialStatusBaseBase): pass

class DCLineInitialStatusBase(DCLineInitialStatusBaseBase): pass

