import logging
from datamodel.input.staticinnerbase import *

class BusInitialStatus(BusInitialStatusBase): pass

class ShuntInitialStatus(ShuntInitialStatusBase): pass

class DispatchableDevices_SimpleProducingConsumingDevicesInitialStatus(DispatchableDevices_SimpleProducingConsumingDevicesInitialStatusBase): pass

class ACTransmissionLineInitialStatus(ACTransmissionLineInitialStatusBase): pass

class TwoWindingTransformerInitialStatus(TwoWindingTransformerInitialStatusBase): pass

class DCLineInitialStatus(DCLineInitialStatusBase): pass

